[package]
name = "stereo_matching"
version = "0.1.0"
authors = ["Daulet <batayev.d@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.0"
rand = "0.7.0"